### ISSUE TITLE
Unable to setup!

### ISSUE THREAD

**Issue by dguzman1012** [whitef0x0/tellform#147]
Hello!!! 

I have installed the last version of tellform into an Instance on Aws.

All requirements and dependences are done but i am still unable to see the sign in form.

![error_tellform](https://cloud.githubusercontent.com/assets/5767551/23182809/3f974ea4-f850-11e6-82a5-c63370ffed7f.png)

BTW: i have done a correct configuration into Apache with a reverse proxy in order to show only domain and not domain:3000 (I have done this before for others nodejs webapps so i'm pretty sure it is not the problem).

Does anyone have idea about this??? Thanks

**Comment by dguzman1012** [comment]
Now when i change the NODE_ENV to "production" it just show me an AngularJS Error: 

![error_in_production](https://cloud.githubusercontent.com/assets/5767551/23184588/c6990bee-f856-11e6-98b9-29c66ac22e89.png)

Thanks for your interest

**Comment by whitef0x0** [comment]
@dguzman1012 you have to set your BASE_URL to whatever url you are using for your server. Aka for the hosted site, (at admin.tellform.com), the BASE_URL is admin.tellform.com

**Comment by dguzman1012** [comment]
actualy i did it... i use my.domain.com and i set that domain into BASE_URL. Still nothing

**Comment by whitef0x0** [comment]
@dguzman1012 can you click on the second error and show me the page that renders?

**Comment by membranepotential** [comment]
Hey I am having exactly the same problem. Trying to access the site i get `Page not found,      is not a valid path`. In the console it tells me 404 on / and 401 on /users/me. The url is set to /#!/forms. 

In the node logs is a list of https://... entries, maybe this points to a problem? I am not running on https at the moment. 

I am running nginx in proxy configuration, but trying to access the node server directly with port 3000 also gives this error. Base path is set to my subdomain. NODE_ENV=production.

I also tried the docker image, but it gives me the same error. 

I am happy to help with debugging, but some guidance would be appreciated, because I am really out of ideas for now.

Cheers =)

**Comment by whitef0x0** [comment]
@membranepotential Well, it expects you to have access to the root domain. You can run the admin panel on a subdomain though.

**Comment by membranepotential** [comment]
Ok thank you, I will switch the site to the root domain and report back

**Comment by membranepotential** [comment]
Thank you very much, running the site on a regular domain (like http://example.com) instead of a subdomain (like http://subdomain.example.com) and setting the BASE_PATH accordingly fixed the issue for me.

**Comment by whitef0x0** [comment]
@membranepotential awesome! Yea I'll add that to the README. Just busy fixing other bugs right now but I'll put it in the queue.

**Comment by jemus42** [comment]
Hm, after much trial and error I finally found this issue, because that's exactly what I'm trying to do. I assumed I was having issues with docker, as I'm just starting to use it.

Am I correct to assume that currently there's now way to properly deploy tellform on a subdomain?  
Because, well, that would be handy :/

**Comment by whitef0x0** [comment]
@jemus42 @dguzman1012 @membranepotential I've just added a SUBDOMAINS_DISABLED ENV variable that's working in the stage branch. If you set SUBDOMAINS_DISABLED=TRUE in your .env file while using the stage branch it should work.

**Comment by dguzman1012** [comment]
@whitef0x0 Wow man... Thank you very much!!! let me try it!

**Comment by whitef0x0** [comment]
@dguzman Donations.are,always welcome if you ever feel generous
